### ISSUE TITLE
Replace Filter List URL

### ISSUE THREAD

**Issue by The-Commissioner** [CHEF-KOCH/NoScript-Whitelist#11]
uBlock is subscribed with Adguard's Annoyances Filter List:
`https://filters.adtidy.org/extension/chromium/filters/14.txt`

-I suggest changing this with uBlock specific filter list for better compatibility.
-Firefox users maynot benefit much from chromium specific filter list(https://filters.adtidy.org/extension/firefox/filters/14.txt)

For general audience such as ours, let's change the URL to uBlock-tied:-
`https://filters.adtidy.org/extension/ublock/filters/14.txt`

**Comment by CHEF-KOCH** [comment]
Seems all good to me, thanks for your effort to open an ticket to explain and show you commits, but you not need to do that. 

Just comment in your commits and I/others see it then. I always can revert it if necessary.

**Comment by The-Commissioner** [comment]
I have not committed this change yet, I was just suggesting, please have a look.

**Comment by CHEF-KOCH** [comment]
Seems okay, about Firefox, I need to test this but I'm sure as long the list itself not breaks anything it should be okay to merge.

**Comment by The-Commissioner** [comment]
I will check and update about this tomorrow.
