### ISSUE TITLE
NoScript author's sites shouldn't be whitelisted

### ISSUE THREAD

**Issue by hook54321a** [CHEF-KOCH/NoScript-Whitelist#13]
These are the ones of his that I've found so far:
noscript.net
maone.net
hackademix.net
informaction.com

**Comment by CHEF-KOCH** [comment]
I normally close every request without any explanation but I'm curious - why should this not be whitelisted? External ressources like e.g. flattr are already blocked so I see no reason to do this.

**Comment by hook54321a** [comment]
As far as I can tell, the websites work without being on the whitelist. More importantly though, the NoScript dev doesn't have a good reputation. They have put ads on their site that ask users to install malicious software, and they at one point made it so their was built-in anti-adblock in the NoScript addon specifically for their site.
