### ISSUE TITLE
NoScript Future?!

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/NoScript-Whitelist#16]
Hello, this is maybe a little bit shocking because the project is called 'NoScript'-Whitelist but to be perfectly honest with you guys I'm not using NoScript anymore and I'm also not anymore interested in supporting or maintaining the addon-list because for me the better solution is uMatrix. NoScript was once a good addon until Mozilla decided to copy yet another stuff from Chrome, aka WebExtension which pissed me off and other developers too because in most of the cases it forced you to re-write the entire addon because at some point it's better to start over. Because of this, together with Firefox changes, NoScript becomes more and more useless, it can take control over JavaScript, per-site basis but Firfox can do the same, of course not with such a neat option/button but it's in the options - However, the point is that the old function to protect against XSS and Co. are gone and this was the main reason why I used it, not only to control JavaScript, moreover because it was an entire 'suite' of integrated security mechanims which are all gone now - I switched to uMatrix because it can control much more currently, like cookies, scripts, frames, CSS & more. I see this now as a 'suite' which can be used for good in the right hands.

It's up to you, if someone wants to maintain the list I'll let it in the repo but if there is no interest then I will remove it and maybe rename the entire project here.

I will let this ticket 1 month open, if no one makes any suggestion or say he want to maintain it I'll make the switch.

Btw thanks to Mozilla for destroying NoScript .. hope it was worth ... 👍

**Comment by X8716e** [comment]
2 questions:

1. I could wait until tomorrow, get on my desktop & see exact v of FF I’ve got & in which version have they destroyed NoScript - I only temp allow sites every time, no matter when/what site; i’ve always found it a good habit - I use the absolute strictest rules beyond that for behavior re: untrusted sites etc. & like you very much like its XSS & clickjacking protections. My untrusted list is likely larger than many people could tolerate. Same thing with Request Policly continued. My question is what version FF have they introduced those supposed features? I use FF ext release 52.x; just unsure of the decimal. 
2. Is it strictly the NoScript database you want to be rid of? If so, we can certainly discuss it further; thus far I’m interested. Probably a lot of people will always use NoScript, despite what’s going on.

QuickJava is another tool I use among many. Regardless I’ve found the answer to my 1st question. QuickJava says is useless on FF57+ but they’re leaving it up for anyone who can still use it.

**Comment by CHEF-KOCH** [comment]
Uargh your sentences are hard to understand, I assume you're not a native English speaker. 

1) Temp. allowing is not really what I want because even legit/harmless or your favourite sites including third-party CDNs which delivering things which the site has no control over, like the recent YouTube mining scandal - this is the reason a blacklist makes a lot of sense, to avoid that even 'good' sites not delivering you malware. Feel free to post your list and we can see, it could help for uBlock & Co.

2) Yes, it's only NoScript, I would merge it into uMatrix so that the bad domains are blocked and the good ones by default allowed to avoid that you need to have configure each page manually each time.

**Comment by X8716e** [comment]
Apologies; I am a native speaker. I’m extremely overtired, hence my haphazard writing. My own reason in not using even a safe whitelist is simply this: one never knows. Talk more when I’m better able to think.

**Comment by X8716e** [comment]
QuickJava is certainly useless for Java for the reason you state; however the extension also conviently blocks JS, cookies, css, flash (also just about dead), images, animated images, & has a proxy toggle. Regardless, let’s talk more at another time. Thank-you.

**Comment by The-Commissioner** [comment]
Can you install and review no-script again. I think it has underwent some change from the last time you used it.

**Comment by CHEF-KOCH** [comment]
I close it, I do not see any benefit of NoScript (webextensions) compared to solutions we already have like e.g. uMatrix.
