### ISSUE TITLE
[Chromium based Browsers] uMatrix crashes when accessing 'My Rules'

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/NoScript-Whitelist#4]
- ~~Since Chrome 59+ (On Firefox it seems to work)~~ **Update**: Seems to affect only Chromium-based browsers.
- uMatrix 1.0.0 (or higher)
- Access 'My Rules' Panel with a lot of entries
- Extension first hangs and you can't load any new site (because uM is stuck), resetting the rules doesn't help!

![wdw](https://user-images.githubusercontent.com/727123/29976879-dad07a9e-8f3b-11e7-99d9-83ae607a52c6.gif)

**Comment by CHEF-KOCH** [comment]
Fixed with 62.0.3175.0 (491407) + uMatrix 1.0.1.

**Comment by CHEF-KOCH** [comment]
Not fixed at all it seems.

**Comment by mlsad3** [comment]
I just hit this after doing a pull-and-merge of rules from another computer. I clicked 'commit' of the temporary rules, and now it hangs and eventually crashes.

**Comment by mlsad3** [comment]
Looking at Chrome task manager, the extension starts using 100% of a CPU core, and starts jumping from 300MB to 1.2GB of RAM. Then after several "Should Chrome wait for this unresponsive page" popups, the extension finally crashes.
When I go to a website, the extension shows up normally and displays which scripts it is allowing as expected.

**Comment by CHEF-KOCH** [comment]
This urgent shit isn't fixed for months now, I'm not able to provide update rulesets unless this gets fixed. 

I already started over like 6 times creating rules for uMatrix I'm definitely not doing it again, especially if I run soon or later into the same thing. 

This is really annoying. 💩

**Comment by CHEF-KOCH** [comment]
Resolved with uMatrix 1.3.8+.
